// "use client"
import Navbar from '@/components/Navbar';
import './globals.css';
// import { Inter, Roboto } from 'next/font/google';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });
// by default all components renders on the server side but if you want to render any component on client side then just use "use client" at the top of the file

export const metadata = {
  title: 'AJ Dev',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <header>Header</header> */}
        <Navbar />
        {children}
        {/* <footer>Footer</footer> */}
        <Footer />
      </body>
    </html>
  );
}
